version: '2'

services:
  curza-app:
    container_name: curza-app
    image: node:10.15
    restart: always
    working_dir: /app
    command: npm start
    volumes:
     - ./src/app:/app
    environment:
      REACT_APP_WP_API_URL: '${WP_API_URL}'
      REACT_APP_WP_API_PREFIX: '${WP_API_PREFIX}'

  curza-haproxy:
    container_name: curza-haproxy
    image: haproxy:1.9
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./config/haproxy/crt-list.txt:/usr/local/etc/haproxy/crt-list.txt
      - ./config/haproxy/certs:/etc/ssl/certs
