version: '2'

services:
  react:
    image: node:10.15
    restart: always
    working_dir: /app
    command: npm start
    volumes:
     - ./src/app:/app
    environment:
      REACT_APP_WP_API_URL: '${WP_API_URL}'
      REACT_APP_WP_API_PREFIX: '${WP_API_PREFIX}'
      REACT_APP_PROGRAMAS_URL: '${PROGRAMAS_URL}'
      REACT_APP_PROGRAMAS_PREFIX: '${PROGRAMAS_PREFIX}'  
      REACT_APP_PROGRAMAS_ROUTE: '${PROGRAMAS_ROUTE}'
    ports:
      - "${FRONT_PORT}:3000"

  wordpress:
    restart: always
    image: wordpress
    volumes:
     - ./src/wordpress:/var/www/html
     - ./config/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      FRONTEND_URL: '${FRONTEND_URL}'
      WP_API_PREFIX: '${WP_API_PREFIX}'
      WORDPRESS_DB_HOST: 'curza-db'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
    ports:
      - "${BACK_PORT}:80"

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
     - ./data/mysql:/var/lib/mysql

  dbadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    external_links:
      - db:db
    ports:
      - "${DBADMIN_PORT}:80"

  haproxy:
    image: haproxy:1.9
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./config/haproxy/crt-list.txt:/usr/local/etc/haproxy/crt-list.txt
      - ./config/haproxy/certs:/etc/ssl/certs