version: '2'

services:
  curza-app:
    container_name: curza-app
    image: node:10.15
    restart: always
    working_dir: /app
    command: npm start
    volumes:
     - ./src/app:/app
    environment:
      REACT_APP_WP_API_URL: '${WP_API_URL}'
      REACT_APP_WP_API_PREFIX: '${WP_API_PREFIX}'

  curza-haproxy:
    container_name: curza-haproxy
    image: haproxy:1.9
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./config/haproxy/crt-list.txt:/usr/local/etc/haproxy/crt-list.txt
      - ./config/haproxy/certs:/etc/ssl/certs

  curza-wordpress:
    restart: always
    container_name: curza-wordpress
    image: wordpress
    volumes:
     - ./src/wordpress:/var/www/html
     - ./config/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WP_API_PREFIX: '${WP_API_PREFIX}'
      WORDPRESS_DB_HOST: 'curza-db'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
    ports:
      - 8030:80

  curza-db:
    container_name: curza-db
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
     - ./data/mysql:/var/lib/mysql
